REDIRECTS = [
  { :from => "/contributing-to-rubys-documentation", :to => "/2011/05/10/contributing-to-ruby-s-documentation.html"},
  { :from => "/the-first-week-of-rstatus-users-press-scaling", :to => "/2011/03/30/the-first-week-of-rstat-us-users-press-scaling-oh-my.html" },
  { :from => "/announcing-rstatus", :to => "/2011/03/23/announcing-rstat-us.html" },
  { :from => "/did-you-hear-im-ruby-mendicant-universitys-fi", :to => "/2011/03/18/did-you-hear-i-m-ruby-mendicant-university-s-first-visiting-teacher.html" },
  { :from => "/im-quitting-hacker-news", :to => "/2011/03/03/i-m-quitting-hacker-news.html" },
  { :from => "/a-few-notes-on-foucault", :to => "/2011/01/22/a-few-notes-on-foucault.html" },
  { :from => "/goals-for-2011", :to => "/2011/01/02/goals-for-2011.html" },
  { :from => "/hackety-hack-v10", :to => "/2010/12/25/hackety-hack-v1-0.html" },
  { :from => "/the-hardest-decision-ive-ever-made", :to => "/2010/11/17/the-hardest-decision-i-ve-ever-made.html" },
  { :from => "/2010/11/17/the-hardest-decision-i-ve-ever-made.html", :to => "http://localhost:9292/2010/09/24/trolling-is-a-art.html" },
  { :from => "/80-of-success-is-showing-up", :to => "/2010/09/21/80-of-success-is-showing-up.html" },
  { :from => "/trouble-with-diaspora", :to => "/2010/09/17/trouble-with-diaspora.html" },
  { :from => "/a-word-about-why-whyday-and-hackety-hack", :to => "/2010/08/19/a-word-about-why-whyday-and-hackety-hack.html" },
  { :from => "/a-blip-in-time", :to => "/2010/07/24/a-blip-in-time.html" },
  { :from => "/what-to-know-before-debating-type-systems-0", :to => "/2010/07/17/what-to-know-before-debating-type-systems.html" },
  { :from => "/case-study-in-being-excellent-divvy", :to => "/2010/06/30/case-study-in-being-excellent-divvy.html" },
  { :from => "/productivity-waves", :to => "/2010/06/08/productivity-waves.html" },
  { :from => "/you-are-terrified-of-your-own-children-since", :to => "/2010/05/01/you-are-terrified-of-your-own-children-since-they-are-natives-in-a-world-where-you-will-always-be-immigrants.html" },
  { :from => "/a-break-with-the-past", :to => "/2010/04/27/a-break-with-the-past.html" },
  { :from => "/living-in-the-cloud-14", :to => "/2010/04/24/living-in-the-cloud.html" },
  { :from => "/book-review-rework", :to => "/2010/03/10/book-review-rework.html" },
  { :from => "/create-a-more-compelling-experience-for-your", :to => "/2010/03/08/create-a-more-compelling-experience-for-your-users-through-game-mechanics.html" },
  { :from => "/writing-a-su-feature-with-authlogic", :to => "/2010/03/05/writing-a-su-feature-with-authlogic.html" },
  { :from => "/why-bother-creating", :to => "/2010/03/03/why-bother-creating.html" },
  { :from => "/reddit-drama-an-interesting-look-at-community", :to => "/2010/03/01/reddit-drama-an-interesting-look-at-community-values.html" },
  { :from => "/the-hackety-mainfesto", :to => "/2009/12/31/the-hackety-mainfesto.html" },
  { :from => "/the-little-coders-predicament", :to => "/2009/12/28/the-little-coder-s-predicament.html" },
  { :from => "/about-crows", :to => "/2009/12/02/about-crows.html" },
  { :from => "/2011/09/23/more-rstat-dot-us-refatoring.html", :to => "/2011/09/23/more-rstat-dot-us-refactoring.html" },
  { :from => "/posts/2012-1-23-introducing-metadown.markdown", :to => "/posts/2012-01-23-introducing-metadown.markdown" },
  { :from => "/posts/2012-08-13-protological-control--an-introduction", :to => "http://words.steveklabnik.com/protological-control-an-introduction" },
]

